tags:
  - name: categories
    description: categories API

paths:
  # [GET] authors
  /authors:
    get:
      tags:
        - authors
      summary: Find All Authors
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] authors
    post:
      tags:
        - authors
      summary: Add Author
      parameters:
        - name: body
          in: body
          description: Author Data
          required: true
          schema:
            $ref: '#/definitions/authors'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] authors/id
  /authors/{id}:
    get:
      tags:
        - authors
      summary: Find Author By Id
      parameters:
        - name: id
          in: path
          description: Author Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] authors/id
    put:
      tags:
        - authors
      summary: Update Author By Id
      parameters:
        - name: id
          in: path
          description: Author Id
          required: true
          type: integer
        - name: body
          in: body
          description: Author Data
          required: true
          schema:
            $ref: '#/definitions/authors'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] authors/id
    delete:
      tags:
        - authors
      summary: Delete Author By Id
      parameters:
        - name: id
          in: path
          description: Author Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] categories
  /categories:
    get:
      tags:
        - categories
      summary: Find All Categories
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] categories
    post:
      tags:
        - categories
      summary: Add Category
      parameters:
        - name: body
          in: body
          description: Category Data
          required: true
          schema:
            $ref: '#/definitions/categories'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] categories/id
  /categories/{id}:
    get:
      tags:
        - categories
      summary: Find Category By Id
      parameters:
        - name: id
          in: path
          description: Category Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] categories/id
    put:
      tags:
        - categories
      summary: Update Category By Id
      parameters:
        - name: id
          in: path
          description: Category Id
          required: true
          type: integer
        - name: body
          in: body
          description: Category Data
          required: true
          schema:
            $ref: '#/definitions/categories'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] categories/id
    delete:
      tags:
        - categories
      summary: Delete Category By Id
      parameters:
        - name: id
          in: path
          description: Category Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] comments
  /comments:
    get:
      tags:
        - comments
      summary: Find All Comments
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] comments
    post:
      tags:
        - comments
      summary: Add Comment
      parameters:
        - name: body
          in: body
          description: Comment Data
          required: true
          schema:
            $ref: '#/definitions/comments'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] comments/id
  /comments/{id}:
    get:
      tags:
        - comments
      summary: Find Comment By Id
      parameters:
        - name: id
          in: path
          description: Comment Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] comments/id
    put:
      tags:
        - comments
      summary: Update Comment By Id
      parameters:
        - name: id
          in: path
          description: Comment Id
          required: true
          type: integer
        - name: body
          in: body
          description: Comment Data
          required: true
          schema:
            $ref: '#/definitions/comments'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] comments/id
    delete:
      tags:
        - comments
      summary: Delete Comment By Id
      parameters:
        - name: id
          in: path
          description: Comment Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] posts
  /posts:
    get:
      tags:
        - posts
      summary: Find All Posts
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] posts
    post:
      tags:
        - posts
      summary: Add Post
      parameters:
        - name: body
          in: body
          description: Post Data
          required: true
          schema:
            $ref: '#/definitions/posts'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] posts/id
  /posts/{id}:
    get:
      tags:
        - posts
      summary: Find Post By Id
      parameters:
        - name: id
          in: path
          description: Post Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] posts/id
    put:
      tags:
        - posts
      summary: Update Post By Id
      parameters:
        - name: id
          in: path
          description: Post Id
          required: true
          type: integer
        - name: body
          in: body
          description: Post Data
          required: true
          schema:
            $ref: '#/definitions/posts'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] posts/id
    delete:
      tags:
        - posts
      summary: Delete Post By Id
      parameters:
        - name: id
          in: path
          description: Post Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] users
  /users:
    get:
      tags:
        - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

    # [POST] users
    post:
      tags:
        - users
      summary: Add User
      parameters:
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [GET] users/id
  /users/{id}:
    get:
      tags:
        - users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          description: User Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [PUT] users/id
    put:
      tags:
        - users
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
          type: integer
        - name: body
          in: body
          description: user Data
          required: true
          schema:
            $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

    # [DELETE] users/id
    delete:
      tags:
        - users
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          description: user Id
          required: true
          type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# definitions
definitions:
  authors:
    type: object
    required:
      - firstName
      - lastName
    properties:
      firstName:
        type: string
        description: Author First Name
      lastName:
        type: string
        description: Author Last Name

  categories:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: Category Name

  comments:
    type: object
    required:
      - postId
      - content
    properties:
      postId:
        type: number
        description: Post ID
      name:
        type: string
        description: Name of commentor
      content:
        type: string
        description: Comment Content

  posts:
    type: object
    required:
      - title
      - content
    properties:
      title:
        type: string
        description: Post title
      description:
        type: string
        description: Post description
      content:
        type: string
        description: Post content

  users:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

schemes:
  - https
  - http
